fixtures:
  repositories:
    concat: 'https://github.com/puppetlabs/puppetlabs-concat'
    stdlib: 'https://github.com/puppetlabs/puppetlabs-stdlib'
    python: 'https://github.com/stankevich/puppet-python'
    epel: 'https://github.com/stahnma/puppet-module-epel.git'
    systemd: 'https://github.com/camptocamp/puppet-systemd'
